apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
      - name: fleetman-mongodb
        image: mongo:3.6.23
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: "/data/db"
          name: fleetman-mongodb-pv   # Utilisez le même nom que dans le PersistentVolume
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: fleetman-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetman-mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/mongo-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleetman-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: fleetman-mongodb
  volumeName: fleetman-mongodb-pv