apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
      - name: fleetman-position-simulator
        image: supinfo4kube/position-simulator:1.0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
# L'énoncé exige un service par déploiement. Cependant, ce déploiement n'expose aucun port.
# Or, il est impossible de créer un service sans exposer de port. Il ne serait pas raisonnable des ports sans raison.
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: fleetman-position-simulator
# spec:
#   selector:
#     app: fleetman-position-simulator
#   type: ClusterIP
