apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleetman-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: fleetman-mongodb