apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
      - name: fleetman-mongodb
        image: mongo:3.6.23
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        volumeMounts:
          - name: storage
            mountPath: "/data/db"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: fleetman-mongodb-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: fleetman-mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetman-mongodb-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongodb-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleetman-mongodb-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
