apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetman-mongodb-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath  # Vous pouvez ajuster cela en fonction de votre configuration de stockage
  local:
    path: /path/to/your/storage  # Remplacez par le chemin de votre stockage local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - your-node-name  # Remplacez par le nom de votre nœud Kubernetes